### ISSUE TITLE
Fechar janela e atualizar página automática após concluir transação.

### ISSUE THREAD

**Issue by br-it0** [HenriqueCacerez/QRCode-PIX-MercadoPago-php#1]
Fala grande, boa noite!
Muito bom o sistema, estou estudando ele e já consegui fazer algumas coisas, mas tenho uma dúvida.
Não estou conseguindo adicionar back url e entender um pouco mais a fundo como funciona a comunicação com a API.

Qual seria o meio mais prático de fechar a janela após a transação obter o resultado de sucess?

**Comment by KerlonThiago** [comment]
eu pago o qr code e no banco de dados ainda fica pendente, já coloquei pra atualizar de 5 em 5 segundos e nada...
